[package]
name = "stormy_skies"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.5", features = ["nightly", "csr"] }
serde = { version = "1.0.196", features = ["rc"] }
serde_json = "1.0.113"
reqwasm = "0.5.0"
thiserror = "1.0.56"
